apiVersion: v1
kind: ReplicationController
metadata:
  name: sumologic-syslog-collect
  labels:
    k8s-app: sumologic-syslog
spec:
  replicas: 1
  selector:
    k8s-app: sumologic-syslog
  template:
    metadata:
      labels:
        k8s-app: sumologic-syslog
        name: sumologic-syslog
    spec:
      containers:
        - name: sumologic
          image: sumologic/collector:latest-syslog
          env:
            - name: SUMO_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: sumo-log-api-keys
                  key: accessid
            - name: SUMO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sumo-log-api-keys
                  key: accesskey
          ports:
           - containerPort: 514

