apiVersion: v1
kind: ReplicationController
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      volumes:
      - name: ssl
        secret:
          secretName: traefik-cert
      - name: config
        configMap:
          name: traefik-conf
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/ssl"
          name: "ssl"
        - mountPath: "/config"
          name: "config"
        ports:
        - containerPort: 10080 # TODO get value from ansible
          hostPort: 80
        - containerPort: 10443 # TODO get value from ansible
          hostPort: 443
        - containerPort: 18080 # TODO get value from ansible 
          hostPort: 8080
        args:
        - --web
        - --configfile=/config/traefik.toml
        - --kubernetes
        #  - --logLevel=DEBUG
