- name: Generating apiserver openssl conf
  local_action: copy content={{ opensslConf }} dest=assets/tls/openssl.cnf force=no
  vars:
      opensslConf: |
        [req]
        req_extensions = v3_req
        distinguished_name = req_distinguished_name
        [req_distinguished_name]
        [ v3_req ]
        basicConstraints = CA:FALSE
        keyUsage = nonRepudiation, digitalSignature, keyEncipherment
        subjectAltName = @alt_names
        [alt_names]
        DNS.1 = kubernetes
        DNS.2 = kubernetes.default
        DNS.3 = kubernetes.default.svc
        DNS.4 = kubernetes.default.svc.cluster.local
        DNS.5 = *.kubernetes.test
        IP.1 = {{k8s_service_ip}}
        {% for host in groups['kubernetes-masters'] %}
        IP.{{loop.index + 1}} = {{hostvars[host]['ansible_ssh_host']}}
        {% endfor %}


  run_once: true

- name: Generate API Server private key
  local_action: command openssl genrsa -out assets/tls/apiserver-key.pem 2048 creates=assets/tls/apiserver-key.pem
  run_once: true
- name: Create apiserver certificate signing request
  local_action: command openssl req -new -key assets/tls/apiserver-key.pem -out assets/tls/apiserver.csr -subj "/CN={{inventory_hostname}}" -config assets/tls/openssl.cnf creates=assets/tls/apiserver.csr
  run_once: true
- name: Sign apiserver certificate
  local_action: command openssl x509 -req -in assets/tls/apiserver.csr -CA assets/tls/ca.pem -CAkey assets/tls/ca-key.pem -CAcreateserial -out assets/tls/apiserver.pem -days 365 -extensions v3_req -extfile assets/tls/openssl.cnf creates=assets/tls/apiserver.pem
  run_once: true
